# test pipeline for integrated cache support

name: $(Date:yyy.MM.dd)$(Rev:.r)

trigger: none
pr: none

resources:
- repo: self

pool:
  vmImage: ubuntu-latest

variables:
  CCACHE_DIR: $(Pipeline.Workspace)/ccache

jobs:
- job: Check
  container:
    image: docker.io/csauer42/cmake-builder
    endpoint: docker-hub-csauer
  steps:
  - task: Cache@2
    inputs:
      key: 'ccache | "$(Agent.OS)" | "$(Build.SourceVersion)"'
      path: $(CCACHE_DIR)
      restoreKeys: | 
        ccache | "$(Agent.OS)" 
    displayName: ccache
  - script: |
      echo "Test pipeline OK"
      echo "File contents before:"
      cat $(Pipeline.Workspace)/ccache/test.f
      if [ ! -d $(Pipeline.Workspace)/ccache ]; then
        echo 'Creating ccache directory'
        mkdir $(Pipeline.Workspace)/ccache
      fi
      echo 'ok' >> $(Pipeline.Workspace)/ccache/test.f
      echo "File contents after:"
      cat $(Pipeline.Workspace)/ccache/test.f
