# test pipeline for integrated cache support

name: $(Date:yyy.MM.dd)$(Rev:.r)

trigger: none
pr: none

resources:
- repo: self

pool:
  vmImage: ubuntu-latest

jobs:
- job: Check
  steps:
  - script: |
      echo "Test pipeline OK"
      which ccache
