# test pipeline for integrated cache support

name: $(Date:yyy.MM.dd)$(Rev:.r)

trigger: none
pr: none

resources:
- repo: self

pool:
  vmImage: ubuntu-latest

variables:
  CCACHE_DIR: $(Pipeline.Workspace)/ccache

jobs:
- job: Check
  steps:
  - bash: |
      sudo apt-get install ccache -y    
      echo "##vso[task.prependpath]/usr/lib/ccache"
    displayName: Install ccache and update PATH to use linked versions of gcc, cc, etc
  - task: Cache@2
    inputs:
      key: 'ccache | "$(Agent.OS)"'
      path: $(CCACHE_DIR)
      restoreKeys: | 
        ccache | "$(Agent.OS)"
    displayName: ccache
  - script: |
      echo "Test pipeline OK"
      echo "File contents before:"
      cat $(Pipeline.Workspace)/ccache/test.f
      if [ ! -d $(Pipeline.Workspace)/ccache ]; then
        echo 'Creating ccache directory'
        mkdir $(Pipeline.Workspace)/ccache
      fi
      echo 'ok' >> $(Pipeline.Workspace)/ccache/test.f
      echo "File contents after:"
      cat $(Pipeline.Workspace)/ccache/test.f
