# test pipeline for integrated cache support

name: $(Date:yyy.MM.dd)$(Rev:.r)

trigger:
- main

pr: none

resources:
- repo: self

pool:
  vmImage: ubuntu-latest

variables:
  CCACHE_DIR: $(Build.SourcesDirectory)/ccache

jobs:
- job: Test_Cache
  container:
    image: docker.io/csauer42/cmake-builder
    endpoint: docker-hub-csauer42
  steps:
  - task: Cache@2
    inputs:
      key: 'test-cache | "$(Agent.OS)" | "$(Build.SourceVersion)"'
      path: $(CCACHE_DIR)
      restoreKeys: | 
        ccache | "$(Agent.OS)" 
    displayName: ccache
  - script: |
      echo "Test pipeline OK"
      echo "File contents before:"
      cat $(Build.SourcesDirectory)/ccache/test.f
      if [ ! -d $(Build.SourcesDirectory)/ccache ]; then
        echo 'Creating ccache directory: $(Build.SourcesDirectory)/ccache'
        mkdir $(Build.SourcesDirectory)/ccache
      fi
      echo '$(Build.SourceVersion)' >> $(Build.SourcesDirectory)/ccache/test.f
      echo "File contents after:"
      cat $(Build.SourcesDirectory)/ccache/test.f
