# test pipeline for integrated cache support

name: $(Date:yyy.MM.dd)$(Rev:.r)

trigger:
- main

pr: none

resources:
- repo: self

pool:
  vmImage: ubuntu-latest

variables:
  CCACHE_DIR: $(Build.SourcesDirectory)/ccache

jobs:
- job: Nonsense
  steps:
  - script: echo "This doesn't have a purpose"
- job: Test_Cache
  container:
    image: docker.io/csauer42/cmake-builder
    endpoint: docker-hub-csauer42
  dependsOn: Nonsense
  steps:
  - task: Cache@2
    inputs:
      key: 'new-cache | "$(Build.BuildId)"'
      path: $(CCACHE_DIR)
      restoreKeys: | 
        new-cache 
    displayName: CCache_Init
  - task: CMake@1
    inputs:
      cmakeArgs: ../
  - task: CMake@1
    inputs:
      cmakeArgs: --build .
  - script: |
      echo "Test pipeline OK"
      if [ ! -d $(CCACHE_DIR) ]; then
        echo 'Creating ccache directory: $(CCACHE_DIR)'
        mkdir $(CCACHE_DIR)
      else
        du -sh $(CCACHE_DIR)
        ls -lah $CCACHE_DIR)
      fi
    displayName: RunChecks
